export type PartOfSpeech =
  | "noun"
  | "verb"
  | "adj"
  | "adv"
  | "pron"
  | "prep"
  | "conj"
  | "art"
  | "num"
  | "part"
  | "interj"
  | "phrase";

export interface Word {
  id: string; // e.g. "de-0137" — stable, independent of freqRank
  lemma: string;
  en: string;
  pos: PartOfSpeech;
  freqRank: number;
  article?: string; // nouns: "der" | "die" | "das"
  plural?: string;
  note?: string;
}

export interface Lexicon {
  schemaVersion: 1;
  words: Word[];
}

export interface GrammarExample {
  de: string;
  en: string;
}

export interface GrammarNote {
  title: string;
  body: string;
  examples: GrammarExample[];
}

export interface ReviseEntry {
  wordId: string;
  exampleDe: string;
  exampleEn: string;
}

export interface Chapter {
  schemaVersion: 1;
  id: string; // e.g. "de-ch003"
  order: number;
  title: string;
  newWords: string[]; // word IDs introduced in this chapter
  german: string[]; // paragraphs with inline {{wordId|text}} refs
  english: string[]; // translation paragraphs
  grammar?: GrammarNote;
  revise: ReviseEntry[];
  tip?: string;
  showCounter: boolean;
}

/** One entry per chapter in the generated book index. */
export interface BookChapterEntry {
  id: string;
  order: number;
  title: string;
  newWords: string[];
  /** min/max freqRank among this chapter's new words (0/0 when none) */
  freqRange: { from: number; to: number };
}

/** Generated by scripts/validate-content.ts — never edited by hand. */
export interface Book {
  schemaVersion: 1;
  lang: string;
  title: string;
  /** The course target the counter measures against, e.g. 3000. */
  goalWords: number;
  /** Chapters the finished course will have, e.g. 60. */
  goalChapters: number;
  /** Words actually published in the lexicon so far. */
  lexiconSize: number;
  chapters: BookChapterEntry[];
}

// ---------------------------------------------------------------------------
// Progress events (append-only log)
// ---------------------------------------------------------------------------

export type ReviewResult = "known" | "unsure";

export type ProgressEventType =
  | "chapter_opened"
  | "chapter_finished"
  | "chapter_unfinished"
  | "translation_revealed"
  | "word_reviewed";

export interface ProgressEventPayload {
  chapterId?: string;
  wordId?: string;
  result?: ReviewResult;
}

export interface ProgressEvent {
  id: string; // UUID, generated on the device
  userId: string; // "local" in phase 1
  deviceId: string;
  type: ProgressEventType;
  payload: ProgressEventPayload;
  createdAt: string; // ISO timestamp
  schemaVersion: 1;
}

/** Shape of an exported/imported event log file. */
export interface EventLogExport {
  schemaVersion: 1;
  exportedAt: string;
  events: ProgressEvent[];
}
